### ISSUE TITLE
Safe handle missed trailing semicolon

### ISSUE THREAD

**Issue by 0xGeorgii** [OpenZeppelin/sgp#3]
Example:

```solidity
function get_array_length(uint256[] memory _data) public returns (uint256 size) {
    size = _data.length
}
```

Instead of exception, thrown here:
https://github.com/OpenZeppelin/sgp/blob/8e3e74664722fea25ae95732da7e1b1e8f5ffcab/sgp/sgp_visitor.py#L1138

Need to raise an exception to be handled by:
https://github.com/OpenZeppelin/sgp/blob/8e3e74664722fea25ae95732da7e1b1e8f5ffcab/sgp/sgp_error_listener.py#L14

It will prevent the Exception raising here:
https://github.com/OpenZeppelin/sgp/blob/8e3e74664722fea25ae95732da7e1b1e8f5ffcab/sgp/sgp_parser.py#L72

And produces an instance of:
https://github.com/OpenZeppelin/sgp/blob/8e3e74664722fea25ae95732da7e1b1e8f5ffcab/sgp/sgp_error_listener.py#L5

Which can be handled further by a user

UPD: alternately, a grammar can be changed to allow such construction

**Comment by josepchetrit12** [comment]
@0xGeorgii can you handle the following case, it's when `_data` doesn't exist.

```solidity
function get_array_length() public returns (uint256 size) {
    size = _data.length;
}
```

**Comment by 0xGeorgii** [comment]
@josepchetrit12 yes, it doesn't matter since it is not a structural grammar miss
